DROP INDEX L_SHIPDATE_IDX;

DROP INDEX N_NAME_IDX;

DROP INDEX C_MKTSEGMENT_IDX;

DROP INDEX O_ORDERDATE_IDX;

DROP INDEX P_TYPE_P_BRAN_IDX;

DROP INDEX P_TYPE_P_SIZE_IDX;

DROP INDEX S_COMMENT_IDX;

ALTER SESSION SET EVENTS = 'immediate trace name flush_cache';


DROP TABLE CUSTOMERS CASCADE CONSTRAINT;
DROP TABLE LINEITEMS CASCADE CONSTRAINT;
DROP TABLE NATIONS CASCADE CONSTRAINT;
DROP TABLE ORDERSS CASCADE CONSTRAINT;
DROP TABLE PARTS CASCADE CONSTRAINT;
DROP TABLE PARTSUPPLIERS CASCADE CONSTRAINT;
DROP TABLE REGIONS CASCADE CONSTRAINT;
DROP TABLE SUPPLIERS CASCADE CONSTRAINT;

/*
DROP TABLESPACE CAT1
INCLUDING CONTENTS AND DATAFILES;

DROP TABLESPACE CAT2
INCLUDING CONTENTS AND DATAFILES;
*/
